//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSHEProjektArbeit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlCulatorBD : DbContext
    {
        public AlCulatorBD()
            : base("name=AlCulatorBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Personen> Personen { get; set; }
        public virtual DbSet<Re_Su> Re_Su { get; set; }
        public virtual DbSet<Rezepte> Rezepte { get; set; }
        public virtual DbSet<Substanzen> Substanzen { get; set; }
    }
}
