//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSHEProjektArbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personen
    {
        public int Id { get; set; }
        public int Alter { get; set; }
        public int Gewicht { get; set; }
        public int Groesse { get; set; }
        public bool Geschlecht { get; set; }
        public string Name { get; set; }
    }
}
