//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSHEProjektArbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Su
    {
        public int Id { get; set; }
        public int Rezept_ID { get; set; }
        public int Substanz_ID { get; set; }
        public int Menge { get; set; }
    
        public virtual Rezepte Rezepte { get; set; }
        public virtual Substanzen Substanzen { get; set; }
    }
}
